title: Kane Armstrong - Resume
url: ''
baseurl: ''

theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

analytics: UA-163421790-1

sass:
  sass_dir: _sass
  style: compressed

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false